title: "Francis Alvarez"
name: "Francis Alvarez"
description: "Research analyst portfolio"
url: "https://francisalvarez.github.io"
logo: "/assets/images/Francis Cover Photo.jpeg"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
