title: "Francis Alvarez"
name: "Francis Alvarez"
logo: "/assets/images/Francis Cover Photo.jpeg"
description: "Research analyst portfolio"
url: "https://francisalvarez.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

include:
  - _pages
